#!/usr/bin/env bash
# Display information about subdomains.

# Define a function that takes a domain and a subdomain as arguments and prints the record type and destination
display_info () {
	domain="$1"
	subdomain="$2"
	output="$(dig "$subdomain.$domain" A +short)"
	if [ -z "$output" ]; then
		echo "The subdomain $subdomain does not exist or has no A record."
	else
		echo "The subdomain $subdomain is a A record and points to $output"
	fi
}

# Check if the domain argument is provided or not
if [ -z "$1" ]; then
	echo "Usage: $0 domain [subdomain]"
	exit 1
else
	domain=$1
fi

# Check if the subdomain argument is provided or not
if [ -z "$2" ]; then
	display_info "$domain" www
	display_info "$domain" lb-01
	display_info "$domain" web-01
	display_info "$domain" web-02
else
	subdomain="$2"
	display_info "$domain" "$subdomain"
fi
