#!/usr/bin/env bash
# Configure nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update

sudo apt-get -y install nginx

# Create a custom html file that contains 'Hello World!'
echo "Hello World!" | sudo tee /var/www/html/index.html

# Define the string for replacement.
replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.linkedin.com/in/anas-ribki permanent;"

# Use sed to insert redirection config into the default file.
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-enabled/default

# Restart nginx
sudo service nginx restart
