#!/usr/bin/env bash
# Fix nginx listening on port 80 of all the server’s active IPv4 IPs

sudo rm /etc/nginx/sites-enabled/*
sudo ln -s /etc/nginx/sites-available/* /etc/nginx/sites-enabled/
service nginx restart
