#!/usr/bin/env bash
# Make fix short and sweet (service (init) must say that nginx is not running ← for real)
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
pkill -o nginx
