#!/usr/bin/env bash
# Make fix short and sweet (service (init) must say that nginx is not running ← for real)

sudo rm /etc/nginx/sites-enabled/*
sudo ln -s /etc/nginx/sites-available/* /etc/nginx/sites-enabled/
service nginx stop
