#!/usr/bin/env bash
# This script configures the container to run Nginx as nginx user and listen on port 8080
# Usage: ./1-run_nginx_as_nginx

# Edit the Nginx config file to change the user and port
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

chmod 644 /etc/nginx/nginx.conf

pkill apache2

# Start Nginx service
sudo -u nginx service nginx start
